name: Build Image and Upload Artifact

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]  # 可选：当打标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # 仅当推送到 GHCR 时需要

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}        

    - name: Set Lowercase Repository Owner
      run: echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
  

    - name: Get Latest Tag
      id: get_tag
      run: git fetch --tags && echo "LATEST_TAG=$(git tag --sort=-version:refname | head -n 1)" >> $GITHUB_ENV

    - name: Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          docker.io/${{ secrets.DOCKERHUB_REPO_NAME }}/token-founder-twitter:${{ env.LATEST_TAG }}
          docker.io/${{ secrets.DOCKERHUB_REPO_NAME }}/token-founder-twitter:${{ github.sha }}
          ghcr.io/${{ env.REPO_OWNER_LOWER }}/token-founder-twitter:${{ env.LATEST_TAG }}
          ghcr.io/${{ env.REPO_OWNER_LOWER }}/token-founder-twitter:${{ github.sha }}

    # - name: Upload build artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: build-output
    #     path: |
    #       path/to/compiled/files/
    #       another/path/file.exe
    #     retention-days: 5  # 可选，设置保留天数（默认 90）